### PR TITLE
Example

### PR DESCRIPTION
**Pull request by yalh76**
Include https://github.com/YunoHost-Apps/lutim_ynh/tree/simplify-description

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Review by ericgaspar — APPROVED** [review]

**Comment by yalh76** [comment]
@ericgaspar do you know how to fix `Config/panel (actions):       fail `?

**Comment by ericgaspar** [comment]
> @ericgaspar do you know how to fix `Config/panel (actions): fail `?
Something as changes recently that breaks actions... (in Etherpad MyPads, I just set `actions=0` in `check_process`. Actions are going to be rewritten at some point.

**Pull request merged**
